site_name: Point Cloud Utils
repo_url: https://github.com/fwilliams/point-cloud-utils
site_url: https://www.fwilliams.info/point-cloud-utils/
edit_uri: tree/master/docs/docs/
nav:
  - Home: index.md
#  - About: about.md
  - Functionality:
      - "Mesh I/O": sections/mesh_io.md
      - "Point Cloud Resampling": sections/point_cloud_resampling.md
      - "Generating Point Samples on a Mesh": sections/mesh_sampling.md
      - "Shape Metrics": sections/shape_metrics.md
      - "Making a Mesh a Watertight Manifold": sections/watertight_manifold.md
      - "Computing SDFs from Triangle Meshes": sections/mesh_sdf.md
      - "Estimating Normals for a Point Cloud": sections/point_cloud_normal_estimation.md
      - "Computing Mesh Normals": sections/mesh_normal_estimation.md
      - "Ray/Mesh Intersection": sections/ray_mesh_intersection.md
      - "Ray/Surfel Intersection": sections/ray_surfel_intersection.md
      - "Mesh Smoothing": sections/mesh_smoothing.md
  - API Reference:
      - "API Reference": sections/api_reference.md
theme:
  name: readthedocs

markdown_extensions:
  - fenced_code
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      custom_templates: templates
      handlers:
        python:
          options:
            show_source: false
