site_name: Point Cloud Utils
nav:
  - Home: index.md
#  - About: about.md
  - Functionality:
      - "Mesh I/O": sections/mesh_io.md
      - "Point Cloud Resampling": sections/point_cloud_resampling.md
      - "Mesh Sampling": sections/mesh_sampling.md
      - "Shape Metrics": sections/shape_metrics.md
      - "Mesh Signed Distances": sections/mesh_sdf.md
      - "Normal Estimation": sections/normal_estimation.md
      - "Ray/Mesh Intersection": sections/ray_mesh_intersection.md
      - "Mesh Smoothing": sections/mesh_smoothing.md
theme:
  name: readthedocs

markdown_extensions:
  - fenced_code
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkapi:
      src_dirs: ["../../point_cloud_utils"]