site_name: Point Cloud Utils
repo_url: https://github.com/fwilliams/point-cloud-utils
site_url: https://www.fwilliams.info/point-cloud-utils/
edit_uri: tree/master/docs/docs/
nav:
  - Home: index.md
#  - About: about.md
  - Functionality:
      - "Mesh and Point Cloud I/O": sections/mesh_io.md
      - "Resampling Point Clouds": sections/point_cloud_resampling.md
      - "Generating Point Samples on a Mesh": sections/mesh_sampling.md
      - "Point Cloud Metrics": sections/shape_metrics.md
      - "Making a Mesh a Watertight Manifold": sections/watertight_manifold.md
      - "Computing Signed Distances (SDFs) to Meshes": sections/mesh_sdf.md
      - "Estimating Normals for Point Clouds": sections/point_cloud_normal_estimation.md
      - "Computing Mesh Normals": sections/mesh_normal_estimation.md
      - "Ray/Mesh Intersection": sections/ray_mesh_intersection.md
      - "Generating Surfels from Point Clouds": sections/surfels.md
      - "Smoothing a Mesh": sections/mesh_smoothing.md
      - "Decimating a Mesh": sections/mesh_decimation.md
      - "Finding Closest Points Between Point Clouds and Meshes": sections/closest_point_on_mesh.md
      - "Computing Connected Components of a Mesh": sections/computing_connected_components_of_a_mesh.md
      - "Deduplicating Point Clouds and Meshes": sections/deduplicating_point_clouds_and_meshes.md
      - "Calculating Mesh Face Areas": sections/calculating_mesh_face_areas.md
      - "Consistently Orienting Mesh Faces": sections/consistently_orienting_mesh_faces.md
  - API Reference:
      - "API Reference": sections/api_reference.md
theme:
  name: readthedocs

markdown_extensions:
  - fenced_code
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocstrings:
      custom_templates: templates
      handlers:
        python:
          options:
            show_source: false
